language: ruby
sudo: false
cache: bundler
rvm:
  - 2.5.3
before_install:
  - gem update --system
  - gem update --remote bundler

script:
  - bundle exec rake db:setup
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"