language: ruby
rvm:
  - 2.3.8
  - 2.4.0
  - 2.5.3
  - 2.5.7
  
bundler_args: --jobs=2

script:
  - bundle exec rake db:setup
  - bundle exec rake spec
cache: bundler
services:
  - postgresql
addons:
  postgresql: "9.4"