language: ruby
sudo: false
cache: bundler

rvm:
  - 2.5.3
before_install:
  - gem update --system
  - gem install bundler

install: bundle install --retry=3

script:
  - bundle exec rake db:setup
  - bundle exec rake spec

services:
  - postgresql
addons:
  postgresql: "9.4"

notifications:
  email: false